Fix: Set user.is_active to a boolean value
After updating to the open source configmaster version, the LDAP login
failed with:
  ValidationError: [u"'[False, False, False, False, True, False]'
  value must be either True or False."]

closes #24